# Generated by Django 5.2.6 on 2025-10-01 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_completa', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('en camino', 'en camino'), ('entregado', 'entregado'), ('cancelado', 'cancelado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='usuarios.usuario')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
