# Generated by Django 5.2.7 on 2026-06-20 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_alter_rol_table_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar')], max_length=20)),
                ('entidad', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
