# Generated by Django 5.2.7 on 2026-06-20 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_alter_rol_table_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('VIEW', 'Visualización'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('ERROR', 'Error'), ('OTHER', 'Otro')], max_length=20)),
                ('entidad', models.CharField(help_text='Nombre del modelo/tabla afectada (ej: Usuario, Producto, Venta)', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción realizada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'audit_logs',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', '-fecha_hora'], name='audit_logs_usuario_bafa39_idx'), models.Index(fields=['accion', '-fecha_hora'], name='audit_logs_accion_3914cc_idx'), models.Index(fields=['entidad', '-fecha_hora'], name='audit_logs_entidad_9ae29c_idx')],
            },
        ),
    ]
