# Generated by Django 5.2.6 on 2025-10-01 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('esperando', 'esperando'), ('en_atencion', 'en_atencion'), ('finalizado', 'finalizado'), ('cancelado', 'cancelado')], default='esperando', max_length=20)),
                ('prioridad', models.IntegerField(default=0)),
                ('llegada', models.DateTimeField(auto_now_add=True)),
                ('inicio_servicio', models.DateTimeField(blank=True, null=True)),
                ('fin_servicio', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(choices=[('Usuario', 'Usuario'), ('Bot', 'Bot'), ('Empleado', 'Empleado')], max_length=20)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
        ),
    ]
