# Generated by Django 5.2.7 on 2025-11-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mensajechat',
            options={'managed': False},
        ),
    ]
