# Generated by Django 5.2.7 on 2025-11-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_options_alter_mensajechat_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chats',
        ),
        migrations.AlterModelTable(
            name='mensajechat',
            table='mensajes_chat',
        ),
    ]
