# Generated by Django 5.2.7 on 2025-11-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_rol_options_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rol',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
