# Generated by Django 5.2.7 on 2025-10-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_notification_notificationread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
