# Generated by Django 5.2.7 on 2025-11-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_categoria_options_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
    ]
