# Generated by assistant to record the existing DB column `fecha_vencimiento`
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_alter_categoria_table_alter_producto_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="fecha_vencimiento",
            field=models.DateField(null=True, blank=True),
        ),
    ]
