# Generated by Django 5.2.7 on 2025-11-05 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_add_fecha_vencimiento'),
        ('usuarios', '0006_alter_rol_table_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.CharField(choices=[('si', 'si'), ('no', 'no')], default='si', max_length=2)),
            ],
            options={
                'db_table': 'promociones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommended_reason', models.TextField(blank=True, null=True)),
                ('promotion_start', models.DateField(blank=True, null=True)),
                ('promotion_end', models.DateField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, db_constraint=False, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
                ('producto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
