# Generated by Django 5.2.7 on 2025-11-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_promocion_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='tipo',
            field=models.CharField(choices=[('2x1', '2x1'), ('descuento', 'Descuento'), ('oferta', 'Oferta especial')], default='descuento', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=10),
        ),
    ]
