# Generated by Django 5.2.7 on 2025-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_promotion_tipo_alter_promotion_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.TextField(max_length=200, verbose_name='Dirección')),
            ],
        ),
    ]
