# Generated by Django 5.2.7 on 2025-11-30 03:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_empleado'),
        ('usuarios', '0006_alter_rol_table_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('porcentaje_descuento', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_con_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desactivado', 'Desactivado')], default='Activo', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to='productos.producto')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_utilizados', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'cupones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['codigo'], name='cupones_codigo_93d5f5_idx'), models.Index(fields=['estado'], name='cupones_estado_87a76a_idx'), models.Index(fields=['is_deleted'], name='cupones_is_dele_32db9d_idx')],
            },
        ),
    ]
